# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - uses: Gr1N/setup-poetry@v7
      - name: Set config
      - run: |
          poetry config virtualenvs.in-project true
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
      - name: Install dependencies
        run: poetry install
      - name: Publish
        run: poetry publish --build
